# Generated by Django 3.2.13 on 2022-05-02 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Make', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('Governorate', models.CharField(max_length=100)),
                ('Phone_number', models.IntegerField()),
                ('Fuel', models.CharField(max_length=100)),
                ('Engine_Horsepower', models.IntegerField()),
                ('Transmission', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Number_of_seats', models.IntegerField()),
                ('Doors', models.IntegerField()),
                ('Vehicle_description', models.TextField(blank=True)),
                ('Vehicle_extras', models.TextField(blank=True)),
                ('Vehicle_extras_Interior', models.TextField(blank=True)),
                ('Vehicle_extras_Safety', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateField(default=django.utils.timezone.now)),
                ('Predictedprice', models.IntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.FloatField(default=0)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='analyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('puissance_fiscale', models.IntegerField()),
                ('mise_en_circulation', models.IntegerField()),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(max_length=100)),
                ('boite_vitesse', models.CharField(max_length=100)),
                ('gouvernorat', models.CharField(max_length=100)),
            ],
        ),
    ]
